# Generated by Django 5.0.6 on 2024-07-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('numero_identificacion', models.CharField(max_length=25, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña_usuario', models.CharField(max_length=60)),
            ],
        ),
    ]
