# Generated by Django 5.0.6 on 2024-07-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id_usuario',
        ),
    ]
